### ISSUE TITLE
Update Java BDK to Beacon 0.2 API

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#52]
Adapter: https://github.com/mcupak/beacon-of-beacons/tree/master/beacon-adapters/beacon-java
Docs: http://mcupak.github.io/beacon-of-beacons/beacons.html#java
API 0.2: https://docs.google.com/document/d/1hFVqmPDKAs2Tacqta98oIPqUOKlHghmuJD8DtYLQFKw/edit?usp=sharing

Change /query and /info endpoints to generate data in the form according to the new API version.

**Comment by alyh** [comment]
I think this should be reopened because the referenced document contains out of date information. The latest updates to v0.2 API are found here:

https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/beacon.avdl

So for example in `Query` there will need to be an `alternateBases` and `referenceBases`.

**Comment by mcupak** [comment]
Yes, thank you for the comment. I filed a new issue to cover these recent changes: [#70](https://github.com/mcupak/beacon-of-beacons/issues/70).
